# GitHub Actions workflow for testing the Gemini Anti-Truncate Go project

name: Test Gemini Anti-Truncate Go

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Install dependencies
      run: |
        cd gemini-anti-truncate-go
        go mod download
        go mod tidy

    - name: Run unit tests
      run: |
        cd gemini-anti-truncate-go
        go test -v ./internal/...

    - name: Run integration tests
      run: |
        cd gemini-anti-truncate-go
        go test -v ./test/...

    - name: Run coverage tests
      run: |
        cd gemini-anti-truncate-go
        go test -coverprofile=coverage.out ./internal/...
        go tool cover -func=coverage.out

    - name: Run benchmark tests
      run: |
        cd gemini-anti-truncate-go
        go test -bench=. ./test/...

    - name: Run race condition tests
      run: |
        cd gemini-anti-truncate-go
        go test -race ./internal/...

  docker:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        cd gemini-anti-truncate-go
        docker build -t gemini-proxy .

    - name: Test Docker image
      run: |
        cd gemini-anti-truncate-go
        docker run --rm gemini-proxy echo "Docker image is working"